services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    Hschottm\SurveyBundle\:
        resource: '../../{EventListener,DataContainer,Helper,Migration}/*'
        autowire: true
        autoconfigure: true

    Hschottm\SurveyBundle\Helper\CategoryHelper:
        public: true
        autowire: true
        autoconfigure: false